// 统一图标库：基于 lucide-vue-next，集中维护本项目使用的图标。
// 任何组件均可使用 <AppIcon name="xxx" />，name 为下方 map 的 key（kebab 命名）。
// 统一尺寸/线宽/颜色由 AppIcon + global.css 中的 .app-icon 控制。
import {
  Home, FlaskConical, Cpu, BookOpen, CalendarCheck, Compass, Trophy, User, Settings,
  Bell, Clock, ScrollText, AlertTriangle, Download, FileText, FolderOpen, Trash2, Plus,
  Pencil, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, RotateCcw, Inbox, Check, X, Info,
  MessageSquare, Calendar, Gift, PartyPopper, Target, Coins, Gamepad2, Car, ShoppingCart,
  Milk, Lightbulb, Star, Frown, Moon, Search, Link, Globe, GraduationCap, HeartPulse, Mail,
  BarChart, Palette, Brush, LineChart, Github, Hash, Microscope, Folder, PenTool, FileEdit,
  Upload, Paperclip, Pin, Eye, Wifi, Zap, Wrench, Flame, Bookmark, Tag, Sparkles, Award,
  TrendingUp, Users, MessageCircle, BellRing, Save, RefreshCw, Lock, Unlock, Key, Database,
  Filter, PlusCircle, CheckCircle, List, CalendarDays, LayoutDashboard, Image, File, Book,
  SlidersHorizontal, ChartPie, MapPin, ExternalLink, ClipboardList, NotebookPen, School,
  Building2, Stethoscope, Atom, Beaker, Type, Languages, Network, Package, Monitor, Mouse,
  Camera, Printer, Circle,   Brain, Rocket, Shield, Bug, Coffee, Box, HandCoins, Receipt,
  Wallet, Smartphone, Tablet, PanelLeft, Menu, XCircle, HelpCircle, CreditCard, BellDot,
  Flag, ThumbsUp, Send, Share2, ArrowRight, ArrowLeft, ArrowUp, ArrowDown, Minus, Hourglass,
  Timer, BookMarked, FileQuestion, ListChecks, PieChart, Activity, Wand2, Stamp, Ticket,
  ShoppingBag, Heart
} from 'lucide-vue-next'

export const iconMap = {
  'home': Home,
  'flask': FlaskConical,
  'cpu': Cpu,
  'book-open': BookOpen,
  'calendar-check': CalendarCheck,
  'compass': Compass,
  'trophy': Trophy,
  'user': User,
  'settings': Settings,
  'bell': Bell,
  'bell-ring': BellRing,
  'bell-dot': BellDot,
  'clock': Clock,
  'hourglass': Hourglass,
  'timer': Timer,
  'scroll-text': ScrollText,
  'alert-triangle': AlertTriangle,
  'download': Download,
  'upload': Upload,
  'file-text': FileText,
  'file-edit': FileEdit,
  'file': File,
  'file-question': FileQuestion,
  'folder-open': FolderOpen,
  'folder': Folder,
  'trash': Trash2,
  'plus': Plus,
  'plus-circle': PlusCircle,
  'pencil': Pencil,
  'pen-tool': PenTool,
  'notebook-pen': NotebookPen,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'rotate-ccw': RotateCcw,
  'refresh-cw': RefreshCw,
  'inbox': Inbox,
  'check': Check,
  'check-circle': CheckCircle,
  'x': X,
  'x-circle': XCircle,
  'info': Info,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'help-circle': HelpCircle,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'gift': Gift,
  'party-popper': PartyPopper,
  'target': Target,
  'coins': Coins,
  'hand-coins': HandCoins,
  'receipt': Receipt,
  'wallet': Wallet,
  'credit-card': CreditCard,
  'gamepad-2': Gamepad2,
  'car': Car,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'ticket': Ticket,
  'milk': Milk,
  'lightbulb': Lightbulb,
  'star': Star,
  'frown': Frown,
  'moon': Moon,
  'search': Search,
  'link': Link,
  'external-link': ExternalLink,
  'globe': Globe,
  'wifi': Wifi,
  'graduation-cap': GraduationCap,
  'school': School,
  'building-2': Building2,
  'stethoscope': Stethoscope,
  'heart-pulse': HeartPulse,
  'mail': Mail,
  'bar-chart': BarChart,
  'chart-pie': ChartPie,
  'pie-chart': PieChart,
  'activity': Activity,
  'trending-up': TrendingUp,
  'palette': Palette,
  'brush': Brush,
  'beaker': Beaker,
  'atom': Atom,
  'flame': Flame,
  'heart': Heart,
  'zap': Zap,
  'wrench': Wrench,
  'bug': Bug,
  'sparkles': Sparkles,
  'wand-2': Wand2,
  'award': Award,
  'shield': Shield,
  'rocket': Rocket,
  'brain': Brain,
  'bookmark': Bookmark,
  'book': Book,
  'book-marked': BookMarked,
  'tag': Tag,
  'flag': Flag,
  'users': Users,
  'user': User,
  'thumbs-up': ThumbsUp,
  'send': Send,
  'share-2': Share2,
  'image': Image,
  'camera': Camera,
  'monitor': Monitor,
  'mouse': Mouse,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'printer': Printer,
  'package': Package,
  'box': Box,
  'network': Network,
  'database': Database,
  'filter': Filter,
  'sliders': SlidersHorizontal,
  'map-pin': MapPin,
  'clipboard-list': ClipboardList,
  'list': List,
  'list-checks': ListChecks,
  'layout-dashboard': LayoutDashboard,
  'menu': Menu,
  'panel-left': PanelLeft,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'save': Save,
  'paperclip': Paperclip,
  'pin': Pin,
  'eye': Eye,
  'type': Type,
  'languages': Languages,
  'coffee': Coffee,
  'stamp': Stamp,
  'circle': Circle,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'minus': Minus,
  'github': Github,
  'hash': Hash,
  'microscope': Microscope,
  'pen-tool': PenTool,
}

// 判断字符串是否为 emoji（用于兼容旧数据中残留的 emoji 图标）
export function isEmoji(str) {
  if (!str) return false
  return /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{2190}-\u{21FF}\u{2300}-\u{23FF}\u{25A0}-\u{25FF}\u{2705}\u{274C}\u{2713}\u{2717}\u{2764}]/u.test(str)
}
